### ISSUE TITLE
MemoryStream is empty

### ISSUE THREAD

**Issue by Kruemelino** [yasoonOfficial/outlook-dndprotocol#2]
Hi,

thank you for your work. I think, this is exactly what I was looking for. 
Your debug-app works fine. For my work, which is also here at github, i need to convert your code to vb.net (4.0 Client). After I finished this I realized that the MemoryStream is empty. It's not really empty: the length of the stream is not zero, it has the correct size. But even a BinaryReader or a StreamReader can read the stream. 

I wrote a several test forms, but I can not read the Stream. Even such easy c# scripts like the following does not work:
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.IO;

namespace WindowsFormsApplication1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_DragDrop(object sender, DragEventArgs e)
        {
            if (e.Data.GetDataPresent("RenPrivateMessages"))
            {
                MemoryStream dataStream = e.Data.GetData("RenPrivateMessages") as MemoryStream;

                if (dataStream != null)
                {
                    StreamReader sr = new StreamReader(dataStream, Encoding.UTF8);
                    String t = sr.ReadToEnd();
                }
            }
        }
        private void Form1_DragOver(object sender, DragEventArgs e)  {e.Effect = DragDropEffects.Copy;}
        private void Form1_DragEnter(object sender, DragEventArgs e) {e.Effect = DragDropEffects.Copy;}
    }
}

Do you have any idea, what my mistake is?

**Comment by tobiasviehweger** [comment]
Hi,

this is not your mistake. Note that my example app is using WPF windows. This is because the Windows Forms drag and drop have a bug, which manifest the way you mention.

To work around that, you will need to use the the underlying COM drag and drop. I pushed another example project to demonstrate that. It uses some native OLE32 methods to achieve the same thing.
